---
- name: reload snmp_exporter
  systemd:
    name: snmp_exporter
    state: reloaded
  become: true
  tags: snmp_exporter

- name: restart snmp_exporter
  systemd:
    daemon_reload: true
    name: snmp_exporter
    state: restarted
  become: true
  tags: snmp_exporter

- name: reload ufw
  systemd:
    name: ufw
    state: reloaded
  tags: snmp_exporter
  become: true

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  tags: snmp_exporter
  become: true